app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager



class User(UserMixin,db.Model):
    __tablename__ = 'users'


    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email=db.Column(db.String(255),unique=True,index=True)
    password_hash=db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    blog = db.relationship('Blog', backref='user', lazy='dynamic')
    BlogComment = db.relationship('BlogComment', backref='user', lazy='dynamic')
    @property
    def password(self):
        raise AttributeError('You can not read the password Attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return  {self.username}


    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


class Blog(db.Model):
    __tablename__ = 'blog'
    id = db.Column(db.Integer, primary_key=True)
    blog = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    blogdata = db.relationship('BlogComment', backref='use', lazy='dynamic')

    def save_blog(self):
        db.session.add(self)

class BlogComment(db.Model):
    __tablename__ = 'blogcom'
    id = db.Column(db.Integer, primary_key=True)
    blogcom = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    blog_id = db.Column(db.Integer, db.ForeignKey("blog.id"))

    def save_blogcomment(self):
        db.session.add(self)
        db.session.commit()
        
        

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required


class CommentForm(FlaskForm):
    name = StringField('Name', validators=[Required()])
    comment = TextAreaField('Blog comment', validators=[Required()])
    submit = SubmitField('Submit')

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class BlogForm(FlaskForm):
    blog = TextAreaField('Write a blog')
    submit = SubmitField('Submit')

class BlogCommentForm(FlaskForm):
    blogcomment = TextAreaField('Comment on blog ')
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Who are you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()

simple = SimpleMDE()

def create_app(config_name):
    app = Flask(__name__)

    # creating app configurations
    app.config.from_object(config_options[config_name])
    app.config['SECRET_KEY'] = 'abcdef'


    # initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    simple.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # registering the Blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # registering the auth Blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User, Blog, BlogComment
from .. import db
from flask_login import login_required, current_user
from .forms import *
import markdown2


@main.route('/')
def index():

    return render_template('index.html')

@main.route('/blog', methods = ['GET','POST'])
@login_required
def blog():
    form = BlogForm()
    title = 'Blog pitches'
    if form.validate_on_submit():
        new_blog = Blog(blog=form.blog.data, user_id=current_user.id)

        db.session.add(new_blog)
        db.session.commit()
        return redirect(url_for('main.blog'))

    return render_template("blog.html", title = title, blogsform= form)


@main.route('/blog/<int:id>',  methods=['GET', 'POST'])
@login_required
def blog_id(id):

    blog = Blog.query.get(id)
    form = BlogCommentForm()
    if form.validate_on_submit():
        blogcomment = form.blogcomment.data
        new_blogcomment = BlogComment(blogcomment=blogcomment, blog_id=id, user=current_user)
        new_blogcomment.save_blogcomment()

    blogcomment = BlogComment.query.filter_by(blog_id=id).all()
    return render_template('blogies.html',blogform=form, blogcomments = blogcomment, blog=blog)

@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/new/blog/<int:id>',  methods=['GET', 'POST'])
@login_required
def new_blog(id):

    blog = Blog.query.get(id)
    form = BlogCommentForm()
    if form.validate_on_submit():
        blogcomment = form.blogcomment.data
        new_blogcomment = BlogComment(blogcomment=blogcomment, blog_id=id, user=current_user)
        new_blogcomment.save_blogcomment()

    blogcomment = BlogComment.query.filter_by(blog_id=id).all()
    return render_template('blog_view.html',blogform=form, blogcomments = blogcomment, blog=blog)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block -->
{% block navbar %}

    {% include 'navbar.html' %}
    
{% endblock %}

app/templates/bio.html
{% extends 'base.html' %}


{% block content %}
<style>
body, html {
    height: 50%;
    font-family: sans-serif;
}
* {
    box-sizing: border-box;
}
.bg-img {
    
}
.container {
    position: absolute;
    right: 0;
    margin: 20px;
    max-width: 300px;
    padding: 16px;
    background-color: white;
}

.btn {
    background-color: blue;
    color: white;
    padding: 16px 20px;
    border: none;
    cursor: pointer;
    width: 20%;
    opacity: 1;
}
.btn:hover {
    opacity: 1;
}
</style>
</head>


<div classs='container-fluid'>
<div class="bg-img">
  <div class="row">

  <div class="col-md-2"> </div>

        <div class="col-md-8">
            <a href="/blog" >Write a Blog</a></br>
                <h1>All the blogs posted</h1>
                {% for blog in blogs %}
                <blockquote>
                {{blog.blog}}
                </blockquote>
            <a href="/blog/{{blog.id}}"><span class="glyphicon glyphicon-comment"></span></a>
                <h1>{{blog.user.username}}</h1>
                {% endfor %}
                {{simplemde.load}}
        </div>

        <div class="col-md-4"> </div>
    </div>
</div>
</div>


{% endblock %}

app/templates/blog.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<style>
body, html {
    height: 50%;
    font-family: sans-serif;
}
* {
    box-sizing: border-box;
}

.container {
    background-color: white;
    position: absolute;
    right: 0;
    margin: 20px;
    max-width: 150px;
    padding: 16px;
}

.btn {
    background-color: blue;
     padding: 16px 20px;
    border: none;
    cursor: pointer;
    width: 20%;
    color: white;
    opacity: 1;
    font-style: italic;
}
.btn:hover {
    opacity: 1;
}
h1{
    font-style: italic;
}
</style>
</head>


<div classs='container-fluid'>
<div class="bg-img">
  <div class="row">
  <div class="col-md-2"> </div>
        <div class="col-md-8">
      <h1>Write a Blog</h1>
            {{wtf.quick_form(blogsform)}}
        </div>
{{simplemde.load}}
       <div class="col-md-2"> </div>


</div>
</div>
</div>


{% endblock %}

app/templates/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(blogcomment_form)}}

	
	{% if all_comments %}
	<div class="row text-center">
		{% for comment in all_comments %}
	
  <!-- Content -->
  <div class="text-white text-center d-flex align-items-center rgba-black-strong py-5 px-4">
      <h3 class="card-title pt-2"><strong>{{ comment.comments}}</strong></h3>
		<h5 class="pink-text">By: {{comment.user.username}}</h5>
    </div>

{% endfor %}

{% else %}
    <h3>No comments</h3>
{% endif %}
</div>


{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}

    <title> {{ title }} </title>

    <div class="container">

        <h1>Error Page</h1>
        
    </div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% block content %}


<div class="container">

    <div class="row">
        <div class="col-md-8 mb-5">
            <h1>The Blog App</h1>
            <hr>
            <h3>Hello!! WELCOME TO THE BLOG APP</h3>
            <br>

            <p>Here you are able to provide your blogs to the internet and others can post comments on them but first ensure that you create an account with us
            </p>

        </div>
        <br>
        <div class="col-md-4 mb-5">
            <h2>Contact Us</h2>
            <hr>
            <address>

          <br>KASABUNI | KENYA
          <br>
        </address>
            <address>
          <abbr title="Phone">Phone:</abbr>
          0717871486
          <br>
          <abbr title="Email">Email:petermax2004@gmail.com</abbr>
          <a href="mailto:#"></a>
        </address>
        </div>
    </div>

<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; GLobal Blogs 2019</p>
    </div>
</footer>


</body>

{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-amber navbar-inverse" style='margin-bottom: 0px;' role="navigation" id="navigate">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">HOME</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="/blog">NEW BLOG</a></li>
            </ul>


            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}"><span
              class="glyphicon glyphicon-user"></span> Profile</a></li>



                <li><a href="{{url_for('auth.logout')}}"><span class="glyphicon glyphicon-log-out"></span> SIGN OUT </a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}"><span class="glyphicon glyphicon-log-in"></span> SIGN IN </a></li>
                {% endif %}
            </ul>


        </div>

    </div>
</div>

app/templates/new_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container" >

        <div class="col-md-12" style="border:1px solid #222;border-radius: 5px;box-shadow: 5px 10px #888888;">
            {{ wtf.quick_form(blogform) }}
            {{simplemde.load}}
        </div>

    </div>

{% endblock %}

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container-fluid">
    <div class="well" style="border:1px solid #222;border-radius: 5px;box-shadow: 5px 10px #888888;">
        <div class="jumbotron">
            {{ wtf.quick_form(blogcomment_form) }}
        </div>    
            {{macro.displayComments(all_comments)}}
    </div>
</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">

<div class="col-md-2"></div>
<div class="col-md-8">
  <div>
  {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
  {% endif %}
</div>


<!-- displaying  Username-->
  <div>
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div>
  {% if user.profile_pic_path %}

  <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

  {% else %}
  <p>No Profile Picture</p>

  {% endif %}

      {% if user == current_user %}
  <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

    <input type="file"  name="photo" class="form-control" required>
    <input type="submit">
    {% endif %}
</div>


</div>
<div class="col-md-2"></div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}

<style>
body, html {
    height: 50%;
    font-family: sans-serif;
}
* {
    box-sizing: border-box;
}
.bg-img {

}

.container {
    margin: 20px;
    max-width: 300px;
    padding: 16px;
    background-color: white;
    position: absolute;
    right: 0;
   
}

.btn {
    background-color: blue;
    color: white;
    padding: 16px 20px;
    border: none;
    cursor: pointer;
    width: 20%;
    opacity: 1;
    font-style:italic;
}
.btn:hover {
    opacity: 1;
}
</style>
</head>
<body>


<div class="bg-img">
  <div class="row">
  <div class="col-md-2"> </div>
        <div class="col-md-8">
        <!-- Login form -->
        {{wtf.quick_form(form)}}
       </div>
       <div class="col-md-2"> </div>
      </div>




</body>
</html>



{% endblock %}